### ISSUE TITLE
checkbox_other gives exception if other is not listed as an option

### ISSUE THREAD

**Issue by jeffmax** [chop-dbhi/redcap-repeat#8]

**Comment by jeffmax** [comment]
Traceback (most recent call last):
  File "redcap_preprocess.py", line 664, in <module>
    main(args[0], args[1])
  File "redcap_preprocess.py", line 606, in main
    for generated_line in dispatch[line[key['d']]](line):
  File "redcap_preprocess.py", line 185, in details
    new_lines[-1][key['a']] = preserve_metadata("end", "_%s_dtls" % clean(last_detail), line[key['a']])
  File "redcap_preprocess.py", line 92, in clean
    return x.replace(" ","_").replace("/","_").replace("(","_").replace(")","_").lower()
